const slides = [
  {
    id: "slide-1",
    title: "Blue Lagoon, Trogir, Šolta",
    description1: "Hidden beaches & local secrets around island Šolta and Trogir",
    description2: "Perfect for those short on time but big on adventure.",
    poster: "/posters/1.jpg",
    video: "/videos/lagoon.mp4",
    type: "Half day tour",
    price: "700",
    url: "/tours/blue-lagoon-trogir-solta",
  },
  {
    id: "slide-3",
    title: "Blue cave and Five Islands",
    description1: "From Split to Hvar, Pakleni Islands, Vis & the Blue Cave",
    description2: "8 hours of island-hopping, swimming, and dining on your terms.",
    poster: "/posters/3.jpg",
    video: "/videos/blue-cave.mp4",
    type: "Full day tour",
    price: "1400",
    url: "/tours/blue-cave-five-islands",
  },
  {
    id: "slide-2",
    title: "Hvar and Pakleni Islands",
    description1: "From Split to Hvar Town and the secluded Pakleni archipelago",
    description2: "A full day of vibrant culture, hidden coves, and effortless elegance on the Adriatic.",
    poster: "/posters/2.jpg",
    video: "/videos/hvar.mp4",
    type: "Full day tour",
    price: "1200",
    url: "/tours/hvar-and-pakleni-islands",
  },
  {
    id: "slide-4",
    title: "Bol And Golden Horn",
    description1: "From Split to Bol,Hvar Town and the secluded Pakleni archipelago",
    description2: "A full day of vibrant culture, hidden coves, and effortless elegance on the Adriatic.",
    poster: "/posters/2.jpg",
    video: "/videos/hvar.mp4",
    type: "Full day tour",
    price: "1200",
    url: "/tours/hvar-and-pakleni-islands",
  },
];

export default slides;
