const slides = [
  {
    id: "slide-1",
    title: "Blue Lagoon, Čiovo, Trogir & Šolta",
    description: "Swim in the turquoise Blue Lagoon, explore historic Trogir, and unwind on hidden bays of Šolta.",
    poster: "/posters/1.jpg",
    video: "/videos/lagoon.mp4",
    type: "Half day tour",
    price: "700",
    url: "/our-tours/blue-lagoon-trogir-solta",
    image: "/assets/images/tours/lagoon.jpg",
  },
  {
    id: "slide-3",
    title: "Blue Cave & Five Islands",
    description: "Discover the famous Blue Cave, visit Vis, Hvar, Pakleni Islands, and swim in hidden coves.",
    poster: "/posters/3.jpg",
    video: "/videos/blue-cave.mp4",
    type: "Full day tour",
    price: "1400",
    url: "/our-tours/blue-cave-five-islands",
    image: "/assets/images/tours/cave.jpg",
  },
  {
    id: "slide-2",
    title: "Hvar & Pakleni Islands",
    description: "Enjoy Hvar’s vibrant culture and the untouched beauty of the Pakleni archipelago.",
    poster: "/posters/2.jpg",
    video: "/videos/hvar.mp4",
    type: "Full day tour",
    price: "1200",
    url: "/our-tours/hvar-and-pakleni-islands",
    image: "/assets/images/tours/pakleni.jpg",
  },
  {
    id: "slide-4",
    title: "Bol, Golden Horn, Hvar & Pakleni",
    description: "Relax on Croatia’s iconic Golden Horn beach, then explore Hvar Town and Pakleni Islands.",
    poster: "/posters/2.jpg",
    video: "/videos/hvar.mp4",
    type: "Full day tour",
    price: "1200",
    url: "/our-tours/bol-golden-horn-hvar-pakleni",
    image: "/assets/images/tours/zlatni-rat.jpg",
  },
];

export default slides;
